# Application
spring.application.name=pawnrestservice
server.port=${PORT:8080}

# Cloud (Railway) PostgreSQL
spring.datasource.url=jdbc:postgresql://nozomi.proxy.rlwy.net:26527/railway
spring.datasource.username=postgres
spring.datasource.password=VQvUgHqhNxWpOTPVCKAasmfmOovAjGby
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'

# Disable JPA auto-configuration (we use JdbcTemplate only)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
