# Application
spring.application.name=magizhchitechapp
server.port=${PORT:8080}

# File Upload
app.upload.dir=${UPLOAD_DIR:uploads}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pawnbroking}
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

aws.accessKey=${AWS_ACCESS_KEY:}
aws.secretKey=${AWS_SECRET_KEY:}
aws.region=eu-north-1
aws.s3.bucket=thirumarankarunanithibucket

# Desktop app JAR location in S3 (can be a different bucket/key from the main bucket)
aws.s3.app.bucket=thirumarankarunanithibucket
aws.s3.app.key=app/salesdesktopservice-2.0.jar